### ISSUE TITLE
A comparison is missing with the popular existing SIMD/vectorization libraries

### ISSUE THREAD

**Issue by eyalroz** [MorphStore/TVLLib#1]
There are already several well-known/relatively-popular existing libraries for wrapping use of SIMD/vectorized CPU instruction, including:

* [Vc](https://github.com/VcDevel/Vc): "portable, zero-overhead C++ types for explicitly data-parallel programming"
* [tsimd](https://github.com/ospray/tsimd): "Fundamental C++ SIMD types for Intel CPUs"
* [MyIntrinsics++](https://github.com/aff3ct/MIPP) (MIPP): "Wrapper for vector intrinsic functions (SIMD) in C++11. "
* [xsimd](https://github.com/xtensor-stack/xsimd): "C++ wrappers for SIMD extensions"
* Agner Fog's [VectorClass](https://www.agner.org/optimize/#vectorclass): "C++ classes, functions and operators that make it easier to use the the vector instructions (SIMD) of modern CPUs."

and there is even some work towards standardization of SIMD wrappers in C++, see:

* [N4808](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/n4808.pdf): "Working Draft, C++Extensions for Parallelism Version 2"
* ... it's now in the Extensions for Parallelism Technical Specification, v2; see [cppreference](https://en.cppreference.com/w/cpp/experimental/simd) page.

How does TVLLib differ from each of these? Is it better? Simpler? Doing slightly different things? Why develop it, as opposed to adapting or improving the existing libraries? When presenting TVLLib as an independent repository, the motivation for visitors to consider adopting and using it must be made explicit and clear.

Note: Please don't answer these questions _here_; answer them on the README.md page and/or on appropriate wiki pages.

**Comment by the-monster** [comment]
Thank you for the topic suggestion. 
We are well aware that there are other libraries for vectorization. However, a comparison is somewhere between difficult and impossible. The reasons for this are varied and include (amongst others) missing documentation/examples, the need for a fork of an outdated compiler, no support for the instruction set of choice, missing convenience for changing the instruction set, and not being open source/no chance to extend the library. But the most important reason is that simply none of the libraries provided us with the necessary functionality. They were mainly providing sequential memory access and basic arithmetic functionality, which is not sufficient for the use-case of a query execution engine. This is merely enough to implement a simple aggregation, which we did with a C++ extension called [Sierra](https://dl.acm.org/doi/10.1145/2568058.2568062). 
However, a repository forum or a code documentation is not the right place to present such comparisons, but to explain the purpose and usage of  a project. Instead, you can find a comparison and a short discussion of related work in our [CIDR20 paper](http://cidrdb.org/cidr2020/papers/p28-ungethuem-cidr20.pdf).
Please note that this is an academic prototype with limited manpower. Thus, there will not be an extensive comparison of each and every operation for each library.
Again, thank you for your interest in our Template Vector Library.

**Comment by eyalroz** [comment]
@the-monster : I didn't mean a comparison in the sense of benchmarks or an exhaustive design overview. I meant it in the sense of piquing the curiosity of GitHub visitors. A person notices the TVLLib repository, and thinks "Oh, ok, here's another SIMD templatization library. Should I try it? ... It doesn't have many stars. What's special about it? What is its 'angle' or relative advantage, which would make me pick it over other, more popular libraries?"

It looks like you have several good answers to that question:

* "Here's a snippet of code which shows how TVLLib can do X, which most/all other libraries cannot."
* "Doing Y is tricky, we document it well, something which  [most](link1) [other](link2) [libraries](link3) don't."

and so on. My point is that if you've made TVLLib an independent project - and if you want users and perhaps contributors - you should do a bit more to attract them. And this should not take more than a hour or two of work IMHO.

Of course that is all entire up to you.
