### ISSUE TITLE
Several primitives have parameters of type int whose width is not uniform across platforms.

### ISSUE THREAD

**Issue by pdamme** [MorphStore/TVLLib#2]
For instance, int might be 4 or 8 byte, depending on the system. Therefore, int should not be used if the base type is uint64_t. I suggest generally using the uintX_t types. I stumbled upon this issue with the create-primitives, however, it might be present elsewhere as well, we should check that.

**Comment by pdamme** [comment]
@the-monster, @JPietrzykTUD: It would be great if you could have a look at that problem and whether my fix for two of the occurrences is satisfactory, once you have some spare time.

**Comment by the-monster** [comment]
Todays update does not include any generic int anymore :)
