### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rana** [MorphStore/TVLLib#5]
Hi,

Thank you for your innovative contributions. I'm enjoying reading your paper [Hardware-Oblivious SIMD Parallelism for In-Memory
Column-Stores](http://cidrdb.org/cidr2020/papers/p28-ungethuem-cidr20.pdf), and others.

Would you be willing to offer a license to your GitHub repositories? It is unclear how your repositories can be used in other works.

Thank you,

Rana

**Comment by the-monster** [comment]
Hi Rana,

Thank you for taking the time to look into our work. We decided to license the TVL under Apache 2.0. The according license file can now be found in the root folder. If you are going to use our code, make sure to watch the repository as we are currently harmonizing all primitive interfaces.

Best regards
Annett
